name: eea-noise-cdn

on:
  workflow_dispatch:

permissions:
  contents: write
  id-token: write

jobs:
  eea-noise:
    uses: ./.github/workflows/cdn-manifest.yml
    secrets: inherit
    with:
      harvests: |
        [
          {"bin":"eea_noise_compiler","netloc":"eea.europa.eu","asset":"eea_noise_2025.json"}
        ]
