name: frb-chime-cdn

on:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  frb-chime:
    uses: ./.github/workflows/cdn-manifest.yml
    secrets: inherit
    with:
      harvests: |
        [
          {"bin":"frb_compiler","netloc":"cdsarc.cds.unistra.fr","asset":"frb_chime_cat1.json"}
        ]
