name: hadisst-cdn

on:
  workflow_dispatch:
  schedule:
    - cron: '37 6 1 * *'

permissions:
  contents: write

jobs:
  hadisst:
    uses: ./.github/workflows/cdn-manifest.yml
    secrets: inherit
    with:
      harvests: |
        [
          {"bin":"hadisst_compiler","netloc":"metoffice.gov.uk","asset":"hadisst_sst.bin","refresh":true}
        ]
