name: impc-roti-cdn

on:
  workflow_dispatch:
  schedule:
    - cron: '17 * * * *'

permissions:
  contents: write
  id-token: write

jobs:
  impc-roti:
    uses: ./.github/workflows/cdn-manifest.yml
    secrets: inherit
    with:
      harvests: |
        [
          {"bin":"impc_roti_compiler","netloc":"data.impc.dlr.de","asset":"impc_roti.bin","refresh":true}
        ]
