name: lro-trk-cdn

on:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  lro-trk:
    uses: ./.github/workflows/cdn-manifest.yml
    secrets: inherit
    with:
      harvests: |
        [
          {"bin":"lro_trk_compiler","netloc":"imbrium.mit.edu","asset":"lro_trk.bin","refresh":true}
        ]
